import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk';
import {
  AUDIT_TARGETS,
  PROJECT_ROOT,
  resolveFromProjectRoot
} from './util/constants.js';

const createId = (prefix) => `${prefix}-${crypto.randomUUID()}`;

const createFinding = ({
  category = 'pages',
  severity = 'medium',
  description,
  evidence,
  recommendationId = null
}) => ({
  id: createId('finding'),
  category,
  severity,
  description,
  evidence,
  ...(recommendationId ? { recommendationId } : {})
});

const createRecommendation = ({
  action,
  impact = 'DX',
  effort = 'low',
  status = 'proposed',
  relatedFindingIds = []
}) => ({
  id: createId('rec'),
  relatedFindingIds,
  action,
  impact,
  effort,
  status
});

const fileExists = async (filePath) => {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
};

const safeReadFile = async (filePath) => {
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch {
    return null;
  }
};

export const run = async ({ target = AUDIT_TARGETS.PAGES } = {}) => {
  const findings = [];
  const recommendations = [];
  const diagnostics = [];

  const frontendDir = resolveFromProjectRoot('astro-frontend');
  const wranglerJsoncPath = path.join(frontendDir, 'wrangler.jsonc');
  const rootWranglerTomlPath = resolveFromProjectRoot('wrangler.toml');
  const deployScriptPath = resolveFromProjectRoot('scripts', 'deploy-frontend.sh');
  const frontendPackageJsonPath = path.join(frontendDir, 'package.json');

  // ── Check 1: astro-frontend/ directory existence ──────────────────────
  console.log(chalk.dim('  Checking astro-frontend/ directory...'));

  const frontendExists = await fileExists(frontendDir);

  if (!frontendExists) {
    findings.push(
      createFinding({
        category: 'pages',
        severity: 'info',
        description: 'Pages audit: astro-frontend/ directory not found',
        evidence:
          'The astro-frontend/ directory does not exist. Run ./setup.sh to generate it. ' +
          'This is expected before first setup.'
      })
    );

    diagnostics.push({
      level: 'info',
      message: 'astro-frontend/ not found — skipping frontend-specific checks'
    });
  }

  // ── Check 2: wrangler.jsonc existence and content ─────────────────────
  console.log(chalk.dim('  Checking wrangler.jsonc...'));

  if (frontendExists) {
    const wranglerJsoncExists = await fileExists(wranglerJsoncPath);

    if (!wranglerJsoncExists) {
      const finding = createFinding({
        category: 'pages',
        severity: 'info',
        description: 'Pages audit: wrangler.jsonc not found in astro-frontend/',
        evidence:
          `Expected Pages config at ${path.relative(PROJECT_ROOT, wranglerJsoncPath)} — ` +
          'this file is generated by setup.sh'
      });
      findings.push(finding);

      recommendations.push(
        createRecommendation({
          action: 'Run ./setup.sh to generate astro-frontend/wrangler.jsonc with Pages configuration',
          impact: 'correctness',
          effort: 'low',
          relatedFindingIds: [finding.id]
        })
      );

      diagnostics.push({
        level: 'warning',
        message: 'wrangler.jsonc missing — Pages deploy may fail'
      });
    } else {
      const wranglerContent = await safeReadFile(wranglerJsoncPath);

      if (wranglerContent !== null) {
        diagnostics.push({
          level: 'info',
          message: `wrangler.jsonc found (${wranglerContent.length} bytes)`
        });

        // JSONC comment stripping: remove // line comments and /* block comments */ before JSON.parse
        const stripped = wranglerContent
          .replace(/\/\/.*$/gm, '')
          .replace(/\/\*[\s\S]*?\*\//g, '');

        let parsed = null;
        try {
          parsed = JSON.parse(stripped);
        } catch {
          const finding = createFinding({
            category: 'pages',
            severity: 'medium',
            description: 'Pages audit: wrangler.jsonc contains invalid JSON',
            evidence: 'Failed to parse wrangler.jsonc after stripping comments'
          });
          findings.push(finding);

          recommendations.push(
            createRecommendation({
              action: 'Fix JSON syntax in astro-frontend/wrangler.jsonc — verify with a JSON linter',
              impact: 'correctness',
              effort: 'low',
              relatedFindingIds: [finding.id]
            })
          );
        }

        if (parsed) {
          if (!parsed.name) {
            findings.push(
              createFinding({
                category: 'pages',
                severity: 'low',
                description: 'Pages audit: wrangler.jsonc missing "name" field',
                evidence: 'The "name" field identifies the Pages project for deployment'
              })
            );
          } else {
            diagnostics.push({
              level: 'info',
              message: `Pages project name: "${parsed.name}"`
            });
          }

          if (parsed.pages_build_output_dir) {
            diagnostics.push({
              level: 'info',
              message: `pages_build_output_dir: "${parsed.pages_build_output_dir}"`
            });
          }
        }
      }
    }
  }

  // ── Check 3: No legacy wrangler.toml at project root ──────────────────
  console.log(chalk.dim('  Checking for legacy wrangler.toml at project root...'));

  const rootWranglerTomlExists = await fileExists(rootWranglerTomlPath);

  if (rootWranglerTomlExists) {
    const finding = createFinding({
      category: 'pages',
      severity: 'medium',
      description: 'Pages audit: legacy wrangler.toml found at project root',
      evidence:
        'A wrangler.toml exists at the project root. The correct Pages config is ' +
        'astro-frontend/wrangler.jsonc. The root file may be a leftover from an earlier setup.'
    });
    findings.push(finding);

    recommendations.push(
      createRecommendation({
        action: 'Remove the root wrangler.toml — Pages configuration belongs in astro-frontend/wrangler.jsonc',
        impact: 'correctness',
        effort: 'low',
        relatedFindingIds: [finding.id]
      })
    );
  } else {
    diagnostics.push({
      level: 'info',
      message: 'No legacy wrangler.toml at project root — correct'
    });
  }

  // ── Check 4: deploy-frontend.sh existence and dist/ reference ─────────
  console.log(chalk.dim('  Checking deploy script...'));

  const deployScriptExists = await fileExists(deployScriptPath);

  if (!deployScriptExists) {
    const finding = createFinding({
      category: 'pages',
      severity: 'info',
      description: 'Pages audit: deploy-frontend.sh not found',
      evidence: `Expected deploy script at ${path.relative(PROJECT_ROOT, deployScriptPath)}`
    });
    findings.push(finding);

    recommendations.push(
      createRecommendation({
        action: 'Create scripts/deploy-frontend.sh to automate build + wrangler pages deploy',
        impact: 'DX',
        effort: 'medium',
        relatedFindingIds: [finding.id]
      })
    );
  } else {
    const deployContent = await safeReadFile(deployScriptPath);

    if (deployContent !== null) {
      const referencesDistDeploy = /wrangler\s+pages\s+deploy\s+\.\/dist/.test(deployContent);

      if (referencesDistDeploy) {
        diagnostics.push({
          level: 'info',
          message: 'Deploy script correctly deploys ./dist directory via wrangler pages deploy'
        });
      } else {
        const finding = createFinding({
          category: 'pages',
          severity: 'medium',
          description: 'Pages audit: deploy script does not reference ./dist for wrangler pages deploy',
          evidence:
            'Expected "wrangler pages deploy ./dist" in deploy-frontend.sh. ' +
            'The Astro build outputs to dist/ which must be the deploy source.'
        });
        findings.push(finding);

        recommendations.push(
          createRecommendation({
            action: 'Update deploy-frontend.sh to use: npx wrangler pages deploy ./dist --project-name="$PROJECT_NAME"',
            impact: 'correctness',
            effort: 'low',
            relatedFindingIds: [finding.id]
          })
        );
      }

      const referencesBuild = /npm\s+run\s+build/.test(deployContent);

      if (referencesBuild) {
        diagnostics.push({
          level: 'info',
          message: 'Deploy script includes build step (npm run build)'
        });
      } else {
        findings.push(
          createFinding({
            category: 'pages',
            severity: 'low',
            description: 'Pages audit: deploy script does not include a build step',
            evidence: 'Expected "npm run build" in deploy-frontend.sh before deploy'
          })
        );
      }
    }
  }

  // ── Check 5: astro-frontend/package.json has build script ─────────────
  console.log(chalk.dim('  Checking frontend package.json...'));

  if (frontendExists) {
    const pkgContent = await safeReadFile(frontendPackageJsonPath);

    if (pkgContent === null) {
      findings.push(
        createFinding({
          category: 'pages',
          severity: 'info',
          description: 'Pages audit: package.json not found in astro-frontend/',
          evidence: 'Expected package.json at astro-frontend/package.json'
        })
      );
    } else {
      let pkg = null;
      try {
        pkg = JSON.parse(pkgContent);
      } catch {
        findings.push(
          createFinding({
            category: 'pages',
            severity: 'medium',
            description: 'Pages audit: astro-frontend/package.json is invalid JSON',
            evidence: 'Failed to parse package.json'
          })
        );
      }

      if (pkg) {
        const hasBuildScript = pkg.scripts && typeof pkg.scripts.build === 'string';

        if (hasBuildScript) {
          diagnostics.push({
            level: 'info',
            message: `Frontend build script: "${pkg.scripts.build}"`
          });
        } else {
          const finding = createFinding({
            category: 'pages',
            severity: 'medium',
            description: 'Pages audit: no "build" script in astro-frontend/package.json',
            evidence: 'A build script is required for static site generation before deploy'
          });
          findings.push(finding);

          recommendations.push(
            createRecommendation({
              action: 'Add "build": "astro build" to scripts in astro-frontend/package.json',
              impact: 'correctness',
              effort: 'low',
              relatedFindingIds: [finding.id]
            })
          );
        }
      }
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────
  const infoFindings = findings.filter((f) => f.severity === 'info').length;
  const actionableFindings = findings.filter((f) => f.severity !== 'info').length;

  diagnostics.push({
    level: 'info',
    message: `Pages config audit complete: ${findings.length} finding(s) (${actionableFindings} actionable, ${infoFindings} informational)`
  });

  return {
    target,
    findings,
    recommendations,
    diagnostics,
    metadata: {
      target,
      frontendDirExists: frontendExists,
      wranglerJsoncExists: frontendExists && (await fileExists(wranglerJsoncPath)),
      rootWranglerTomlExists: rootWranglerTomlExists,
      deployScriptExists: deployScriptExists,
      findingCount: findings.length,
      recommendationCount: recommendations.length
    }
  };
};

export default run;
